// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_envelope.proto
// Protobuf C++ Version: 7.36.0-dev

#include "rpc_envelope.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::minirpc::RpcRequestProto
        {&::_pbi::kDescriptorMethods, &::descriptor_table_rpc_5fenvelope_2eproto, /* tracker*/ nullptr,},
        // ::minirpc::RpcResponseProto
        {&::_pbi::kDescriptorMethods, &::descriptor_table_rpc_5fenvelope_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace minirpc {
class RpcResponseProto::_Internal {
 public:
  using HasBits = decltype(::std::declval<RpcResponseProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_._has_bits_);
};

constexpr RpcResponseProto::ParseTableT_ RpcResponseProto::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::minirpc::RpcResponseProto>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // uint32 sequence_id = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RpcResponseProto, _impl_.sequence_id_), 3>(),
       {32, 3, 0,
        PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.sequence_id_)}},
      // uint32 error_code = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RpcResponseProto, _impl_.error_code_), 2>(),
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.error_code_)}},
      // string error_message = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.error_message_)}},
      // bytes result_data = 3;
      {::_pbi::TcParser::FastBS1,
       {26, 1, 0,
        PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.result_data_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 error_code = 1;
      {PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.error_code_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // string error_message = 2;
      {PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.error_message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bytes result_data = 3;
      {PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.result_data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // uint32 sequence_id = 4;
      {PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.sequence_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
      "\30\0\15\0\0\0\0\0"
      "minirpc.RpcResponseProto"
      "error_message"
    }},
  };
}


inline constexpr RpcResponseProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_code_{0u},
        sequence_id_{0u} {}

template <typename>
constexpr RpcResponseProto::RpcResponseProto(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RpcResponseProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RpcResponseProto(arena);
}
constexpr auto RpcResponseProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RpcResponseProto), alignof(RpcResponseProto));
}
constexpr auto RpcResponseProto::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RpcResponseProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RpcResponseProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RpcResponseProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RpcResponseProto>(), &RpcResponseProto::ByteSizeLong,
              &RpcResponseProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_rpc_5fenvelope_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RpcResponseProtoGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RpcResponseProtoGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RpcResponseProto_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RpcResponseProto::InternalGenerateClassData_(
            _default, &RpcResponseProto_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RpcResponseProto>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RpcResponseProtoGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RpcResponseProto _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RpcResponseProto>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RpcResponseProtoGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RpcResponseProtoGlobalsTypeInternal RpcResponseProto_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RpcResponseProto_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RpcResponseProto_globals_.GetClassData();
#else
  return RpcResponseProto_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class RpcRequestProto::_Internal {
 public:
  using HasBits = decltype(::std::declval<RpcRequestProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_._has_bits_);
};

constexpr RpcRequestProto::ParseTableT_ RpcRequestProto::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::minirpc::RpcRequestProto>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // bytes payload = 4;
      {::_pbi::TcParser::FastBS1,
       {34, 2, 0,
        PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.payload_)}},
      // string service_name = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.service_name_)}},
      // string method_name = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.method_name_)}},
      // uint32 sequence_id = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RpcRequestProto, _impl_.sequence_id_), 3>(),
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.sequence_id_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string service_name = 1;
      {PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.service_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string method_name = 2;
      {PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.method_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 sequence_id = 3;
      {PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.sequence_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // bytes payload = 4;
      {PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_.payload_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\27\14\13\0\0\0\0\0"
      "minirpc.RpcRequestProto"
      "service_name"
      "method_name"
    }},
  };
}


inline constexpr RpcRequestProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : service_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        method_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sequence_id_{0u} {}

template <typename>
constexpr RpcRequestProto::RpcRequestProto(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RpcRequestProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RpcRequestProto(arena);
}
constexpr auto RpcRequestProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RpcRequestProto), alignof(RpcRequestProto));
}
constexpr auto RpcRequestProto::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RpcRequestProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RpcRequestProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RpcRequestProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RpcRequestProto>(), &RpcRequestProto::ByteSizeLong,
              &RpcRequestProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RpcRequestProto, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_rpc_5fenvelope_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RpcRequestProtoGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RpcRequestProtoGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RpcRequestProto_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RpcRequestProto::InternalGenerateClassData_(
            _default, &RpcRequestProto_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RpcRequestProto>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RpcRequestProtoGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RpcRequestProto _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RpcRequestProto>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RpcRequestProtoGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RpcRequestProtoGlobalsTypeInternal RpcRequestProto_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RpcRequestProto_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RpcRequestProto_globals_.GetClassData();
#else
  return RpcRequestProto_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace minirpc
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_rpc_5fenvelope_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_rpc_5fenvelope_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpc_5fenvelope_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcRequestProto, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcRequestProto, _impl_.service_name_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcRequestProto, _impl_.method_name_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcRequestProto, _impl_.sequence_id_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcRequestProto, _impl_.payload_),
        0,
        1,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcResponseProto, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcResponseProto, _impl_.error_code_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcResponseProto, _impl_.error_message_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcResponseProto, _impl_.result_data_),
        PROTOBUF_FIELD_OFFSET(::minirpc::RpcResponseProto, _impl_.sequence_id_),
        2,
        0,
        1,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::minirpc::RpcRequestProto)},
        {11, sizeof(::minirpc::RpcResponseProto)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::minirpc::RpcRequestProto_globals_,
        &::minirpc::RpcResponseProto_globals_,
};
const char descriptor_table_protodef_rpc_5fenvelope_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022rpc_envelope.proto\022\007minirpc\"b\n\017RpcRequ"
    "estProto\022\024\n\014service_name\030\001 \001(\t\022\023\n\013method"
    "_name\030\002 \001(\t\022\023\n\013sequence_id\030\003 \001(\r\022\017\n\007payl"
    "oad\030\004 \001(\014\"g\n\020RpcResponseProto\022\022\n\nerror_c"
    "ode\030\001 \001(\r\022\025\n\rerror_message\030\002 \001(\t\022\023\n\013resu"
    "lt_data\030\003 \001(\014\022\023\n\013sequence_id\030\004 \001(\rb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_rpc_5fenvelope_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_5fenvelope_2eproto = {
    false,
    false,
    242,
    descriptor_table_protodef_rpc_5fenvelope_2eproto,
    "rpc_envelope.proto",
    &descriptor_table_rpc_5fenvelope_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_rpc_5fenvelope_2eproto::offsets,
    file_level_enum_descriptors_rpc_5fenvelope_2eproto,
    file_level_service_descriptors_rpc_5fenvelope_2eproto,
};
namespace minirpc {
// ===================================================================

RpcRequestProto::RpcRequestProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcRequestProto_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:minirpc.RpcRequestProto)
}
PROTOBUF_NDEBUG_INLINE RpcRequestProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::minirpc::RpcRequestProto& from_msg)
      : _has_bits_{from._has_bits_},
        service_name_(arena, from.service_name_),
        method_name_(arena, from.method_name_),
        payload_(arena, from.payload_) {}

RpcRequestProto::RpcRequestProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RpcRequestProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcRequestProto_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RpcRequestProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sequence_id_ = from._impl_.sequence_id_;

  // @@protoc_insertion_point(copy_constructor:minirpc.RpcRequestProto)
}
PROTOBUF_NDEBUG_INLINE RpcRequestProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : service_name_(arena),
        method_name_(arena),
        payload_(arena) {}

inline void RpcRequestProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sequence_id_ = {};
}
RpcRequestProto::~RpcRequestProto() {
  // @@protoc_insertion_point(destructor:minirpc.RpcRequestProto)
  SharedDtor(*this);
}
inline void RpcRequestProto::SharedDtor(MessageLite& self) {
  RpcRequestProto& this_ = static_cast<RpcRequestProto&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.service_name_.Destroy();
  this_._impl_.method_name_.Destroy();
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RpcRequestProto_class_data_ =
        RpcRequestProto::InternalGenerateClassData_(RpcRequestProto_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcRequestProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcRequestProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RpcRequestProto_class_data_.tc_table);
  return RpcRequestProto_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcRequestProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcRequestProto_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RpcRequestProto_globals_));
  return RpcRequestProto_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RpcRequestProto::ParseTableT_
    RpcRequestProto::_table_ =
        RpcRequestProto::InternalGenerateParseTable_(RpcRequestProto_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RpcRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:minirpc.RpcRequestProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.service_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.method_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.sequence_id_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RpcRequestProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RpcRequestProto& this_ = static_cast<const RpcRequestProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RpcRequestProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RpcRequestProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:minirpc.RpcRequestProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string service_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_service_name().empty()) {
      const ::std::string& _s = this_._internal_service_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "minirpc.RpcRequestProto.service_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string method_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_method_name().empty()) {
      const ::std::string& _s = this_._internal_method_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "minirpc.RpcRequestProto.method_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint32 sequence_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_sequence_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_sequence_id(), target);
    }
  }

  // bytes payload = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_payload().empty()) {
      const ::std::string& _s = this_._internal_payload();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:minirpc.RpcRequestProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RpcRequestProto::ByteSizeLong(const MessageLite& base) {
  const RpcRequestProto& this_ = static_cast<const RpcRequestProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RpcRequestProto::ByteSizeLong() const {
  const RpcRequestProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:minirpc.RpcRequestProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string service_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_service_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_service_name());
      }
    }
    // string method_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_method_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_method_name());
      }
    }
    // bytes payload = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_payload());
      }
    }
    // uint32 sequence_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_sequence_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_sequence_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RpcRequestProto::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RpcRequestProto*>(&to_msg);
  auto& from = static_cast<const RpcRequestProto&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:minirpc.RpcRequestProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_service_name().empty()) {
        _this->_internal_set_service_name(from._internal_service_name());
      } else {
        if (_this->_impl_.service_name_.IsDefault()) {
          _this->_internal_set_service_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_method_name().empty()) {
        _this->_internal_set_method_name(from._internal_method_name());
      } else {
        if (_this->_impl_.method_name_.IsDefault()) {
          _this->_internal_set_method_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_payload().empty()) {
        _this->_internal_set_payload(from._internal_payload());
      } else {
        if (_this->_impl_.payload_.IsDefault()) {
          _this->_internal_set_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_sequence_id() != 0) {
        _this->_impl_.sequence_id_ = from._impl_.sequence_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RpcRequestProto::CopyFrom(const RpcRequestProto& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:minirpc.RpcRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RpcRequestProto::InternalSwap(RpcRequestProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_name_, &other->_impl_.service_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_name_, &other->_impl_.method_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  swap(_impl_.sequence_id_, other->_impl_.sequence_id_);
}

::google::protobuf::Metadata RpcRequestProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

RpcResponseProto::RpcResponseProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcResponseProto_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:minirpc.RpcResponseProto)
}
PROTOBUF_NDEBUG_INLINE RpcResponseProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::minirpc::RpcResponseProto& from_msg)
      : _has_bits_{from._has_bits_},
        error_message_(arena, from.error_message_),
        result_data_(arena, from.result_data_) {}

RpcResponseProto::RpcResponseProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RpcResponseProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RpcResponseProto_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RpcResponseProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, error_code_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, error_code_),
           offsetof(Impl_, sequence_id_) -
               offsetof(Impl_, error_code_) +
               sizeof(Impl_::sequence_id_));

  // @@protoc_insertion_point(copy_constructor:minirpc.RpcResponseProto)
}
PROTOBUF_NDEBUG_INLINE RpcResponseProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : error_message_(arena),
        result_data_(arena) {}

inline void RpcResponseProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, error_code_),
           0,
           offsetof(Impl_, sequence_id_) -
               offsetof(Impl_, error_code_) +
               sizeof(Impl_::sequence_id_));
}
RpcResponseProto::~RpcResponseProto() {
  // @@protoc_insertion_point(destructor:minirpc.RpcResponseProto)
  SharedDtor(*this);
}
inline void RpcResponseProto::SharedDtor(MessageLite& self) {
  RpcResponseProto& this_ = static_cast<RpcResponseProto&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  this_._impl_.result_data_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RpcResponseProto_class_data_ =
        RpcResponseProto::InternalGenerateClassData_(RpcResponseProto_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcResponseProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcResponseProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RpcResponseProto_class_data_.tc_table);
  return RpcResponseProto_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RpcResponseProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RpcResponseProto_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RpcResponseProto_globals_));
  return RpcResponseProto_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RpcResponseProto::ParseTableT_
    RpcResponseProto::_table_ =
        RpcResponseProto::InternalGenerateParseTable_(RpcResponseProto_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RpcResponseProto::Clear() {
// @@protoc_insertion_point(message_clear_start:minirpc.RpcResponseProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.error_message_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.result_data_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.error_code_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sequence_id_) -
        reinterpret_cast<char*>(&_impl_.error_code_)) + sizeof(_impl_.sequence_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RpcResponseProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RpcResponseProto& this_ = static_cast<const RpcResponseProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RpcResponseProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RpcResponseProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:minirpc.RpcResponseProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 error_code = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_error_code() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_error_code(), target);
    }
  }

  // string error_message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_error_message().empty()) {
      const ::std::string& _s = this_._internal_error_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "minirpc.RpcResponseProto.error_message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bytes result_data = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_result_data().empty()) {
      const ::std::string& _s = this_._internal_result_data();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // uint32 sequence_id = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_sequence_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_sequence_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:minirpc.RpcResponseProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RpcResponseProto::ByteSizeLong(const MessageLite& base) {
  const RpcResponseProto& this_ = static_cast<const RpcResponseProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RpcResponseProto::ByteSizeLong() const {
  const RpcResponseProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:minirpc.RpcResponseProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string error_message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_error_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error_message());
      }
    }
    // bytes result_data = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_result_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_result_data());
      }
    }
    // uint32 error_code = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_error_code() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_error_code());
      }
    }
    // uint32 sequence_id = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_sequence_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_sequence_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RpcResponseProto::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RpcResponseProto*>(&to_msg);
  auto& from = static_cast<const RpcResponseProto&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:minirpc.RpcResponseProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_error_message().empty()) {
        _this->_internal_set_error_message(from._internal_error_message());
      } else {
        if (_this->_impl_.error_message_.IsDefault()) {
          _this->_internal_set_error_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_result_data().empty()) {
        _this->_internal_set_result_data(from._internal_result_data());
      } else {
        if (_this->_impl_.result_data_.IsDefault()) {
          _this->_internal_set_result_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_error_code() != 0) {
        _this->_impl_.error_code_ = from._impl_.error_code_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_sequence_id() != 0) {
        _this->_impl_.sequence_id_ = from._impl_.sequence_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RpcResponseProto::CopyFrom(const RpcResponseProto& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:minirpc.RpcResponseProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RpcResponseProto::InternalSwap(RpcResponseProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.result_data_, &other->_impl_.result_data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.sequence_id_)
      + sizeof(RpcResponseProto::_impl_.sequence_id_)
      - PROTOBUF_FIELD_OFFSET(RpcResponseProto, _impl_.error_code_)>(
          reinterpret_cast<char*>(&_impl_.error_code_),
          reinterpret_cast<char*>(&other->_impl_.error_code_));
}

::google::protobuf::Metadata RpcResponseProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace minirpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_5fenvelope_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
